from tkinter import *
from tkinter import messagebox
from tkinter.ttk import *
import mysql.connector
from screenf import *        
def signupfinal():
        
    parent.destroy()
    top = Tk()  
    top.geometry("1000x700")
    bg1=PhotoImage(file="yo.png")
    canvas2= Canvas(top, width = 1000, height = 700)
    canvas2.pack(fill = "both", expand = True)
    canvas2.create_image( 0, 0, image = bg1, anchor = "nw")
    style1 = Style()
    style1.configure('W.TLabel', font = ('Lucida Calligraphy', 20, 'bold'))
    style2 = Style()
    style2.configure('W.TButton', font = ('Engravers MT', 20, 'bold'))
    def insertsignup():
                conn_siu= mysql.connector.connect(host="localhost",user="root",password="your_password",database="Ambrosia")
                siu_cur=conn_siu.cursor()
                sql=("INSERT INTO USER_DEETS (USERNAME,NAME,EMAIL_ID,MOBILE_NO,ADDRESS,PASSWORD) VALUES (%s, %s, %s, %s, %s, %s);")
                values=(e_1.get(),e_2.get()+e_3.get(),e_4.get(),e_5.get(), e_6.get(),e_7.get())
                siu_cur.execute(sql,values)
                conn_siu.commit()
                messagebox.showinfo("showinfo", "REGISTERED!!!")
                messagebox.showinfo("showinfo", "ENTER USERNAME,PASSWORD AGAIN TO SIGN IN")
                top.destroy()
    username = Label(top, text = "Username", style="W.TLabel").place(x = 50, y = 50) 
    username_canvas = canvas2.create_window( 50, 50, window = username)
    first= Label(top, text = "First Name", style="W.TLabel").place(x = 50, y = 130)
    first_canvas = canvas2.create_window( 50, 130, window = first)
    last= Label(top, text = "Last Name", style="W.TLabel").place(x = 50, y = 210)
    last_canvas = canvas2.create_window( 50, 210, window = last)
    email=Label(top, text = "Email ID", style="W.TLabel").place(x = 50, y = 290)
    email_canvas = canvas2.create_window( 50, 290, window = email)
    mob=Label(top, text = "Mobile number", style="W.TLabel").place(x = 50, y = 370)
    mob_canvas = canvas2.create_window( 50, 390, window = mob)
    ad=Label(top, text = "Address", style="W.TLabel").place(x = 50, y = 450)
    ad_canvas = canvas2.create_window( 50, 450, window = ad)
    password=Label(top, text = "Password", style="W.TLabel").place(x = 50, y = 530)
    password_canvas = canvas2.create_window( 50, 530, window = password)
    submit=Button(top, text = "SUBMIT", style="W.TButton", command = insertsignup).place(x = 130, y = 600)
    submit_canvas = canvas2.create_window( 130, 650, window = submit)
    e_1=StringVar()
    e_2=StringVar()
    e_3=StringVar()
    e_4=StringVar()
    e_5=StringVar()
    e_6=StringVar()
    e_7=StringVar()
    
    
    e1 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_1).place(x = 450, y = 50)
    e2 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_2).place(x = 450, y = 130)  
    e3 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_3).place(x = 450, y = 210)
    e4 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_4).place(x = 450, y = 290)
    e5 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_5).place(x = 450, y = 370)
    e6 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_6).place(x = 450, y = 450)
    e7 = Entry(top, font = ('Bradley Hand ITC',18,'bold'), textvariable = e_7).place(x = 450, y = 530)
    top.mainloop()
    
    top1 = Tk()  
    top1.geometry("1000x700")
    bg1=PhotoImage(file="yo.png")
    canvas2= Canvas(top1, width = 1000, height = 700)
    canvas2.pack(fill = "both", expand = True)
    canvas2.create_image( 0, 0, image = bg1, anchor = "nw")
    style1 = Style()
    style1.configure('W.TLabel', font = ('Lucida Calligraphy', 20, 'bold'))
    style2 = Style()
    style2.configure('W.TButton', font = ('Engravers MT', 20, 'bold'))
    def checksignin():
            conn_siu= mysql.connector.connect(host="localhost",user="root",password="st",database="AMBROSIA")
            siu_cur=conn_siu.cursor()
            sql=("Select * from USER_DEETS where USERNAME = %s and PASSWORD = %s ;")
            values=(e_1n.get(),e_2n.get())
            siu_cur.execute(sql,values)
            info=siu_cur.fetchone()
            if info==None:
                messagebox.showerror("error", "ACCOUNT NOT FOUND")    
            else:
                messagebox.showinfo("showinfo", "SIGNED IN SUCCESSFULLY!!")
                messagebox.showinfo("showinfo", "Hello!Welcome to Ambrosia!!")
                top1.destroy()
                f_f()
            
            
    username = Label(top1, text = "Username", style="W.TLabel").place(x = 50, y = 100) 
    username_canvas = canvas2.create_window( 50, 50, window = username)   
    password=Label(top1, text = "Password", style="W.TLabel").place(x = 50, y = 200)
    password_canvas = canvas2.create_window( 50, 530, window = password)
    submit=Button(top1, text = "SUBMIT", style="W.TButton", command=checksignin).place(x = 130, y = 400)
    submit_canvas = canvas2.create_window( 130, 650, window = submit)
    e_1n=StringVar()
    e_2n=StringVar()
    e1n = Entry(top1, font = ('Bradley Hand ITC',18,'bold'),textvariable=e_1n).place(x = 450, y = 100)  
    e2n=Entry(top1, font = ('Bradley Hand ITC',18,'bold'),textvariable=e_2n).place(x = 450, y = 200)
    top1.mainloop()  
    
def signinfinal():
    parent.destroy()
    top1 = Tk()  
    top1.geometry("1000x700")
    bg1=PhotoImage(file="yo.png")
    canvas2= Canvas(top1, width = 1000, height = 700)
    canvas2.pack(fill = "both", expand = True)
    canvas2.create_image( 0, 0, image = bg1, anchor = "nw")
    style1 = Style()
    style1.configure('W.TLabel', font = ('Lucida Calligraphy', 20, 'bold'))
    style2 = Style()
    style2.configure('W.TButton', font = ('Engravers MT', 20, 'bold'))
    def checksignin():
            conn_siu= mysql.connector.connect(host="localhost",user="root",password="your_password",database="AMBROSIA")
            siu_cur=conn_siu.cursor()
            sql=("Select * from USER_DEETS where USERNAME = %s and PASSWORD = %s ;")
            values=(e_1n.get(),e_2n.get())
            siu_cur.execute(sql,values)
            info=siu_cur.fetchone()
            if info==None:
                messagebox.showerror("error", "ACCOUNT NOT FOUND")    
            else:
                messagebox.showinfo("showinfo", "SIGNED IN SUCCESSFULLY!!")
                messagebox.showinfo("showinfo", "Hello! Welcome to Ambrosia!!")
                top1.destroy()
                f_f()
            
    username = Label(top1, text = "Username", style="W.TLabel").place(x = 50, y = 100) 
    username_canvas = canvas2.create_window( 50, 50, window = username)   
    password=Label(top1, text = "Password", style="W.TLabel").place(x = 50, y = 200)
    password_canvas = canvas2.create_window( 50, 530, window = password)
    submit=Button(top1, text = "SUBMIT", style="W.TButton", command=checksignin).place(x = 130, y = 400)
    submit_canvas = canvas2.create_window( 130, 650, window = submit)
    e_1n=StringVar()
    e_2n=StringVar()
    e1n = Entry(top1, font = ('Bradley Hand ITC',18,'bold'),textvariable=e_1n).place(x = 450, y = 100)  
    e2n=Entry(top1, font = ('Bradley Hand ITC',18,'bold'),textvariable=e_2n).place(x = 450, y = 200)
    top1.mainloop()    


parent = Tk()
parent.geometry("1366x768")
bg= PhotoImage(file="wcs.png")
canvas1= Canvas(parent, width = 1000, height = 702)
canvas1.pack(fill = "both", expand = True)
canvas1.create_image( 0, 0, image = bg, anchor = "nw")
style1 = Style()
style1.configure('W.TButton', font = ('Engravers MT', 20, 'bold'))
 
signup=Button(parent, text = "SIGN UP", command = signupfinal, style="W.TButton")
signin=Button(parent, text = "SIGN IN", command = signinfinal, style="W.TButton")
signup_canvas = canvas1.create_window( 100, 550, anchor = "sw",window = signup)
signin_canvas = canvas1.create_window( 1266, 550, anchor = "se",window = signin)


